- name: variables
  hosts: local
  connection: local
  vars: #PLAY level variables
    COURSE: "Devops with AWS"
    DURATION: "120hrs"
    TRAINER: "vINAY"
  tasks:
  - name: print the variable
    ansible.builtin.debug:
      msg: "course is {{COURSE}} ,{{DURATION}} , trainer is {{TRAINER}},"