- name: variables from files
  hosts: local
  connection: local
  vars_files:
  - vars.yaml
  tasks:
   - name: print course information
   ansible.builtin.debug:
      msg: "course is {{COURSE}} ,{{DURATION}} , trainer is {{TRAINER}}"
     

    