- name: DevOps course information
  hosts: local
  connection: local
  vars:
    course_name: "devops with aws" # string
    duration: 120 #number
    topics:  #list, [] this means list
    - linux
    - shell
    - ansible
    - aws
    live: true #boolean
    tools: #map {} this means map
      ci: jenkins
      cloud: aws
      conatinerization: docker
  tasks:
  - name: print course information
    ansible.builtin.debug:
     msg: "Hello I am learning {{ course_name}},,duration:{{ duration}}, topics are: {{ topics}}, is it live? {{live}}, 
          tools covered are:{{tools}},tools covered  are: {{tools}}"    
