- name: Create EC2 instances and Route53 records
  hosts: local
  connection: local

  vars:
    subnet_id: subnet-067be027dce18c488
    sg_id: sg-0076a822f16f34130
    ami_id: ami-0220d79f3f480ecf5
    instance_type: t3.micro

    instance:
      - mysql
      - backend
      - frontend

  tasks:
  - name: Install AWS Python libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore      

    - name: Create EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        subnet_id: "{{ subnet_id }}"
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        instance_type: "{{ instance_type }}"
      loop: "{{ instance }}"