- name: create-ec2 and r53 records
  connection: local
  hosts: local
  vars:
   subnet_id: subnet-067be027dce18c488
   sg_id: sg-0076a822f16f34130   
   ami_id: ami-0220d79f3f480ecf5
   insatnce_type: t3.micro 
   instance:
   - mysql
   - backend
   - forntend
  tasks:
  - name: create ec2-instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image-id: "{{ ami_id }}"
      insatnce_type: "{{ instance_type }}"
    loop: "{{ instance }}" 